<?php return array (
  'web_title' => '魔豆物流<p><br></p>',
  'web_count' => '<script></script>',
  'web_seo_title' => '魔豆物流公司-魔豆快运公司<p><br></p>',
  'web_seo_keywords' => '<p>魔豆物流</p>',
  'web_seo_description' => '<p>魔豆物流，值得用户信赖！</p>',
  'web_copyright' => '<p>Copyright © 2020 魔豆物流 版权所有</p>',
  'web_url' => '<p>www.deyuanwl.cn</p>',
  'web_ICP' => '<p><br></p>',
  'web_ewm' => '<p style="margin-bottom:0;"><img src="/uploads/07fc15c9d169ee48573edd749d25945d.jpg" style="max-width:100%;"><br></p>',
  'web_mobile' => '<p>130-5239-8503</p>',
  'web_worktime' => '<p>8:30 - 22:00</p>',
  'web_email' => '<p>595452769@qq.com</p>',
  'web_address' => '<p>北京市昌平区</p>',
);